### ISSUE TITLE
error: value of type 'PyVal' has no member 'version'

### ISSUE THREAD

**Issue by terhechte** [pvieito/PythonKit#1]
Hey!

I'm trying to use PythonKit, but it is failing. I'm on the most recent Swift 4.2:

```
> swift --version
Apple Swift version 4.2-dev (LLVM fb6c0e5a49, Clang 5bae8c2e73, Swift 4160301759)
Target: x86_64-apple-darwin17.5.0
```

and my code is rather simple:
``` swift
import PythonKit
let sys = try Python.import("sys")
print("Python Version: \(sys.version)")
```

When I try to compile this, I'm getting the following error:
```
main.swift:6:26: error: value of type 'PyVal' has no member 'version'
print("Python Version: \(sys.version)")
                         ^~~ ~~~~~~~
```

Any idea what this could be?

Thanks!

**Comment by terhechte** [comment]
So it seems that the following code is not being triggered, maybe because I have Swift `4.2-dev` instead of `4.2`? That's weird.

``` swift
#if swift(>=4.2)
...
#endif
```

**Comment by terhechte** [comment]
That indeed seems to be the issue. If I change PythonGlue to `swift(>=4.1)` it works fine. I'll ignore this for now until there's an official Swift 4.2 release.

**Comment by pvieito** [comment]
Yes, it seem even using the Swift 4.2 compiler Swift PM build the package on Swift 4.1 compatibility mode for [_funny_ reasons](https://forums.swift.org/t/swift-4-2-package-swift-and-using-swift-as-a-markup-language/12990). I have updated the `Package.swift` manifest so now it will build with Swift 4.2.
